version: "3.9"

services:
  dibs-backend:
    image: cosmtrek/air
    restart: "no"
    working_dir: /app
    # entrypoint: ["air -c .air.toml"]
    volumes:
      - ./backend/:/app
    ports:
      - 8080:8080
    depends_on:
      - database
      - flyway
    env_file:
      - ./backend/configs/database.env

  database:
    container_name: dibs-database
    image: postgres:16.0
    restart: "no"
    env_file:
        - ./backend/configs/database.env

  flyway:
    image: flyway/flyway:9.22-alpine
    depends_on:
      - database
    volumes:
      - .:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - ./backend/configs/database.env