version: "3.9"

services:
  dibs-backend:
    image: cosmtrek/air
    restart: "no"
    working_dir: /app
    # entrypoint: ["air -c .air.toml"]
    volumes:
      - ./backend/:/app
      - dibs_volume:/app/images
    ports:
      - 8080:8080
    depends_on:
      - database
      - flyway
    env_file:
      - ./backend/configs/database.env

  dibs-client:
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '80:80'
    depends_on:
      - database
      - dibs-backend
    volumes:
      - dibs_volume:/app/images
      - ./client:/app
    

  database:
    container_name: dibs-database
    image: postgres:16.0
    restart: "no"
    env_file:
        - ./backend/configs/database.env

  flyway:
    image: flyway/flyway:9.22-alpine
    depends_on:
      - database
    volumes:
      - .:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - ./backend/configs/database.env

volumes:
  dibs_volume: