# fly.toml app configuration file generated for dibs-backend on 2023-11-29T21:44:57+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dibs-backend"
primary_region = "ams"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[mounts]
  source="dibs_volume"
  destination="/images"
